### PR TITLE
Update  dapr-1.0.0-rc.1.tgz

### PR DESCRIPTION
**Pull request by artursouza**

### CODE REVIEW

**Comment by tcnghia** [comment]
The checksum may change, so you probably have to do a `helm merge` or calculate a new checksum?

**Comment by youngbupark** [comment]
> The checksum may change, so you probably have to do a `helm repo index --url ${{ env.DAPR_HELM_REPO }} --merge index.yaml .`, or calculate a new checksum?
yes.

@artursouza you need to generate index again.

**Comment by artursouza** [comment]
Done. I thought it was 2 separate PRs for that. Now I get it.

**Review by youngbupark — APPROVED** [review]

**Comment by artursouza** [comment]
Please, merge.

**Comment by youngbupark** [comment]
> Please, merge.

DONE

**Pull request merged**
